name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - ".devcontainer/**"
      - ".vscode/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["28"]
        elixir: ["1.19"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
